package cxf.client.demo.complex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-05-08T22:45:29.093+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ComplexService", 
                  wsdlLocation = "docs/ComplexService.wsdl",
                  targetNamespace = "http://demo.client.cxf/") 
public class ComplexService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://demo.client.cxf/", "ComplexService");
    public final static QName ComplexServicePort = new QName("http://demo.client.cxf/", "ComplexServicePort");
    static {
        URL url = ComplexService.class.getResource("docs/ComplexService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ComplexService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "docs/ComplexService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ComplexService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ComplexService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComplexService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComplexService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComplexService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComplexService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ComplexServicePortType
     */
    @WebEndpoint(name = "ComplexServicePort")
    public ComplexServicePortType getComplexServicePort() {
        return super.getPort(ComplexServicePort, ComplexServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComplexServicePortType
     */
    @WebEndpoint(name = "ComplexServicePort")
    public ComplexServicePortType getComplexServicePort(WebServiceFeature... features) {
        return super.getPort(ComplexServicePort, ComplexServicePortType.class, features);
    }

}
